openapi: 3.0.2
info:
  title: API Mapas Culturais V2 - OpenAPI 3.0
  description: |-
    Descreva aqui o que a API do Mapas faz

    Links Importantes:
    - [Mapa Cultural do Ceará](https://mapacultural.secult.ce.gov.br/)
    - [API V2](https://mapacultural.secult.ce.gov.br/api/v2)
    - [Github](https://github.com/secultce/mapacultural)
  contact:
    email: contato@email.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.18
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: /api/v2
tags:
  - name: Espaços
    description: Rotas relacionadas aos espaços
  - name: Selos
    description: Rotas relacionadas aos selos
paths:
  /seals:
    $ref: './components/paths/seal/get-list.yaml'
  /spaces:
    $ref: './components/paths/space/get-list.yaml'
components:
  schemas:
    Seal:
      $ref: './components/schemas/seal.yaml'
    Space:
      $ref: './components/schemas/space.yaml'
