openapi: 3.0.2
info:
  title: API Mapas Culturais V2 - OpenAPI 3.0
  description: |-
    Descreva aqui o que a API do Mapas faz

    Links Importantes:
    - [Mapa Cultural do Ceará](https://mapacultural.secult.ce.gov.br/)
  contact:
    email: contato@email.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.18
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: /v2
