type: object
properties:
  '@entityType':
     type: string
     example: "project"
     description: Tipo de entidade
  id:
     type: integer
     example: 1
     description: ID do projeto
  name:
     type: string
     example: "Projeto de Cultura"
     description: Nome do projeto
  shortDescription:
     type: string
     example: "descrição curta do projeto"
     description: Descrição curta do projeto
  longDescription:
     type: string
     example: "Uma descrição mais detalhada sobre o projeto..."
     description: Descrição detalhada do projeto
  updateTimestamp:
    $ref: "../common-types/date.yaml"
  startsOn:
   type: object
   properties:
     date:
       type: string
       example: "2024-05-01 00:00:00.000000"
       description: Data de início do projeto
     timezone_type:
       type: integer
       example: 3
       description: Tipo de fuso horário
     timezone:
       type: string
       example: "Etc/GMT+3"
       description: Fuso horário
  endsOn:
   type: object
   properties:
     date:
       type: string
       example: "2024-05-31 15:39:00.000000"
       description: Data de término do projeto
     timezone_type:
       type: integer
       example: 3
       description: Tipo de fuso horário
     timezone:
       type: string
       example: "Etc/GMT+3"
       description: Fuso horário
  createTimestamp:
    $ref: "../common-types/date.yaml"
  status:
    type: integer
    example: 1
    description: Status do projeto
  parent:
    type: integer
    example: null
    description: Projeto pai, se aplicável
  owner:
    type: object
    properties:
      '@entityType':
        type: string
        example: "agent"
        description: O tipo de entidade do proprietário
      id:
        type: integer
        example: 1
        description: O ID do proprietário
      name:
        type: string
        example: "Admin@local"
        description: O nome do proprietário
      publicLocation:
        type: string
        example: null
        description: A localização pública do proprietário
      location:
        type: object
        properties:
          latitude:
            type: number
            example: 0
            description: A latitude da localização
          longitude:
            type: number
            example: 0
            description: A longitude da localização
      shortDescription:
        type: string
        example: null
        description: Uma descrição curta do proprietário
      longDescription:
        type: string
        example: null
        description: Uma descrição longa do proprietário
      createTimestamp:
        $ref: '../common-types/date.yaml'
      status:
        type: integer
        example: 1
        description: O status do proprietário
      parent:
        type: string
        example: null
        description: O pai do proprietário
      userId:
        type: integer
        example: 1
        description: O ID do usuário do proprietário
      updateTimestamp:
        $ref: '../common-types/date.yaml'
      subsite:
        type: string
        example: null
        description: O subsite do proprietário
      nomeCompleto:
        type: string
        example: null
        description: O nome completo do proprietário
      nomeSocial:
        type: string
        example: null
        description: O nome social do proprietário
      escolaridade:
        type: string
        example: null
        description: A escolaridade do proprietário
      pessoaDeficiente:
        type: string
        example: null
        description: Se o proprietário é uma pessoa com deficiência
      comunidadesTradicional:
        type: string
        example: null
        description: Se o proprietário pertence a uma comunidade tradicional
      comunidadesTradicionalOutros:
        type: string
        example: null
        description: Outras comunidades tradicionais que o proprietário pertence
      documento:
        type: string
        example: null
        description: O documento do proprietário
      cnpj:
        type: string
        example: ""
        description: O CNPJ do proprietário
      cpf:
        type: string
        example: ""
        description: O CPF do proprietário
      raca:
        type: string
        example: null
        description: A raça do proprietário
      dataDeNascimento:
        type: string
        example: null
        description: A data de nascimento do proprietário
      idoso:
        type: string
        example: null
        description: Se o proprietário é idoso
      localizacao:
        type: string
        example: null
        description: A localização do proprietário
      genero:
        type: string
        example: null
        description: O gênero do proprietário
      orientacaoSexual:
        type: string
        example: null
        description: A orientação sexual do proprietário
      agenteItinerante:
        type: string
        example: null
        description: Se o proprietário é um agente itinerante
      emailPublico:
        type: string
        example: null
        description: O email público do proprietário
      emailPrivado:
        type: string
        example: null
        description: O email privado do proprietário
      telefonePublico:
        type: string
        example: null
        description: O telefone público do proprietário
      telefone1:
        type: string
        example: null
        description: O primeiro telefone do proprietário
      telefone2:
        type: string
        example: null
        description: O segundo telefone do proprietário
      endereco:
        type: string
        example: null
        description: O endereço do proprietário
      En_CEP:
        type: string
        example: null
        description: O CEP do proprietário
      En_Nome_Logradouro:
        type: string
        example: null
        description: O nome do logradouro do proprietário
      En_Num:
        type: string
        example: null
        description: O número do endereço do proprietário
      En_Complemento:
        type: string
        example: null
        description: O complemento do endereço do proprietário
      En_Bairro:
        type: string
        example: null
        description: O bairro do proprietário
      En_Municipio:
        type: string
        example: null
        description: O município do proprietário
      En_Estado:
        type: string
        example: null
        description: O estado do proprietário
      En_Pais:
        type: string
        example: "BR"
        description: O país do proprietário
      site:
        type: string
        example: null
        description: O site do proprietário
      facebook:
        type: string
        example: null
        description: O Facebook do proprietário
      twitter:
        type: string
        example: null
        description: O Twitter do proprietário
      instagram:
        type: string
        example: null
        description: O Instagram do proprietário
      linkedin:
        type: string
        example: null
        description: O LinkedIn do proprietário
      vimeo:
        type: string
        example: null
        description: O Vimeo do proprietário
      spotify:
        type: string
        example: null
        description: O Spotify do proprietário
      youtube:
        type: string
        example: null
        description: O YouTube do proprietário
      pinterest:
        type: string
        example: null
        description: O Pinterest do proprietário
      payment_bank_account_type:
        type: string
        example: null
        description: O tipo de conta bancária para pagamento do proprietário
      payment_bank_account_number:
        type: string
        example: null
        description: O número da conta bancária para pagamento do proprietário
      payment_bank_branch:
        type: string
        example: null
        description: A agência bancária para pagamento do proprietário
      payment_bank_number:
        type: string
        example: null
        description: O número do banco para pagamento do proprietário
      payment_bank_dv_branch:
        type: string
        example: null
        description: O dígito verificador da agência bancária para pagamento do proprietário
      payment_bank_dv_account_number:
        type: string
        example: null
        description: O dígito verificador do número da conta bancária para pagamento do proprietário
      event_importer_processed_file:
        type: object
        description: O arquivo processado pelo importador de eventos
      event_importer_files_processed:
        type: string
        example: "{}"
        description: Os arquivos processados pelo importador de eventos
      sentNotification:
        type: boolean
        example: true
        description: Se a notificação foi enviada
      type:
        type: integer
        example: 1
        description: O tipo do proprietário
      terms:
        type: object
        properties:
          tag:
            type: array
            items:
              type: string
            example: [ ]
            description: As tags do proprietário
          area:
            type: array
            items:
              type: string
            example: [ ]
            description: As áreas do proprietário
          funcao:
            type: array
            items:
              type: string
            example: [ ]
            description: As funções do proprietário
      controllerId:
        type: string
        example: "agent"
        description: O ID do controlador do proprietário
      deleteUrl:
        type: string
        example: "http://localhost/agent/apaga/1/"
        description: A URL para deletar o proprietário
      editUrl:
        type: string
        example: "http://localhost/edicao-de-agente/1/"
        description: A URL para editar o proprietário
      singleUrl:
        type: string
        example: "http://localhost/agente/1/"
        description: A URL do proprietário
      lockedFields:
        type: array
        items:
          type: string
        description: Os campos bloqueados do proprietário
      currentUserPermissions:
        type: object
        properties:
          '@control':
            type: boolean
            example: true
            description: Se o usuário atual tem controle
          create:
            type: boolean
            example: true
            description: Se o usuário atual pode criar
          changeUserProfile:
            type: boolean
            example: true
            description: Se o usuário atual pode alterar o perfil do usuário
          changeType:
            type: boolean
            example: true
            description: Se o usuário pode alterar o tipo
          remove:
            type: boolean
            example: false
            description: Se o usuário pode remover
          destroy:
            type: boolean
            example: false
            description: Se o usuário pode destruir
          changeOwner:
            type: boolean
            example: false
            description: Se o usuário pode alterar o proprietário
          archive:
            type: boolean
            example: false
            description: Se o usuário pode arquivar
          view:
            type: boolean
            example: true
            description: Se o usuário pode visualizar
          modify:
            type: boolean
            example: true
            description: Se o usuário pode modificar
          _control:
            type: boolean
            example: true
            description: Se o usuário tem controle
          viewPrivateFiles:
            type: boolean
            example: true
            description: Se o usuário pode visualizar arquivos privados
          viewPrivateData:
            type: boolean
            example: true
            description: Se o usuário pode visualizar dados privados
          createAgentRelation:
            type: boolean
            example: true
            description: Se o usuário pode criar uma relação de agente
          createAgentRelationWithControl:
            type: boolean
            example: true
            description: Se o usuário pode criar uma relação de agente com controle
          removeAgentRelation:
            type: boolean
            example: true
            description: Se o usuário pode remover uma relação de agente
          removeAgentRelationWithControl:
            type: boolean
            example: true
            description: Se o usuário pode remover uma relação de agente com controle
          createSealRelation:
            type: boolean
            example: true
            description: Se o usuário pode criar uma relação de selo
          removeSealRelation:
            type: boolean
            example: true
            description: Se o usuário pode remover uma relação de selo
          publish:
            type: boolean
            example: false
            description: Se o usuário pode publicar
          unarchive:
            type: boolean
            example: true
            description: Se o usuário pode desarquivar
  subsite:
    type: null
    example: null
    description: Subsite do projeto, se aplicável
  terms:
    type: object
    properties:
      tag:
        type: array
        items:
          type: string
        example: [ "teste" ]
        description: Tags associadas ao projeto
  site:
    type: string
    example: "https://www.google.com.br/?hl=pt-BR"
    description: Site do projeto
  facebook:
    type: string
    example: "Facebook"
    description: Facebook do projeto
  twitter:
    type: string
    example: "twitter"
    description: Twitter do projeto
  instagram:
    type: string
    example: "instagram"
    description: Instagram do projeto
  linkedin:
    type: string
    example: "linkindln"
    description: LinkedIn do projeto
  vimeo:
    type: string
    example: "vimeo"
    description: Vimeo do projeto
  spotify:
    type: string
    example: "spotfy"
    description: Spotify do projeto
  youtube:
    type: string
    example: "youtube"
    description: YouTube do projeto
  pinterest:
    type: string
    example: "pinterest"
    description: Pinterest do projeto
  emailPublico:
    type: string
    example: "email.publico@email.com"
    description: Email público do projeto
  emailPrivado:
    type: string
    example: "email.privado@email.com"
    description: Email privado do projeto
  telefonePublico:
    type: string
    example: "(85) 99999-9999"
    description: Telefone público do projeto
  telefone1:
    type: string
    example: "(85) 99999-9999"
    description: Telefone 1 do projeto
  telefone2:
    type: string
    example: "(85) 99999-9999"
    description: Telefone 2 do projeto
  type:
    type: integer
    example: 16
    description: Tipo do projeto
  controllerId:
    type: string
    example: "project"
    description: ID do controlador do projeto
  deleteUrl:
    type: string
    example: "http://localhost/project/apaga/1/"
    description: URL para deletar o projeto
  editUrl:
    type: string
    example: "http://localhost/edicao-de-projeto/1/"
    description: URL para editar o projeto
  singleUrl:
    type: string
    example: "http://localhost/projeto/1/"
    description: URL do projeto
  lockedFields:
    type: array
    items:
      type: string
    example: [ ]
    description: Campos bloqueados
  currentUserPermissions:
    type: object
    properties:
      '@control':
        type: boolean
        example: true
        description: Se o usuário atual tem controle
      create:
        type: boolean
        example: true
        description: Se o usuário atual pode criar
      modify:
        type: boolean
        example: true
        description: Se o usuário atual pode modificar
      unpublish:
        type: boolean
        example: true
        description: Se o usuário atual pode despublicar
      publish:
        type: boolean
        example: true
        description: Se o usuário atual pode publicar
      view:
        type: boolean
        example: true
        description: Se o usuário atual pode visualizar
      remove:
        type: boolean
        example: true
        description: Se o usuário atual pode remover
      _control:
        type: boolean
        example: true
        description: Se o usuário atual tem controle
      viewPrivateFiles:
        type: boolean
        example: true
        description: Se o usuário atual pode visualizar arquivos privados
      changeOwner:
        type: boolean
        example: true
        description: Se o usuário atual pode alterar o proprietário
      viewPrivateData:
        type: boolean
        example: true
        description: Se o usuário atual pode visualizar dados privados
      createAgentRelation:
        type: boolean
        example: true
        description: Se o usuário atual pode criar uma relação de agente
      createAgentRelationWithControl:
        type: boolean
        example: true
        description: Se o usuário atual pode criar uma relação de agente com controle
      removeAgentRelation:
        type: boolean
        example: true
        description: Se o usuário atual pode remover uma relação de agente
      removeAgentRelationWithControl:
        type: boolean
        example: true
        description: Se o usuário atual pode remover uma relação de agente com controle
      createSealRelation:
        type: boolean
        example: true
        description: Se o usuário atual pode criar uma relação de selo
      removeSealRelation:
        type: boolean
        example: true
        description: Se o usuário pode remover uma relação de selo
      destroy:
        type: boolean
        example: true
        description: Se o usuário pode apagar
      archive:
        type: boolean
        example: true
        description: Se o usuário pode arquivar
      unarchive:
        type: boolean
        example: true
        description: Se o usuário pode desarquivar
